set(ENABLE_PROFILE_GENERATE OFF CACHE BOOL "Enable profile generation")
set(ENABLE_PROFILE_USE OFF CACHE BOOL "Enable profile usage")
set(PROFILE_DIR "pgo" CACHE STRING "Profile directory" FORCE)
if(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
  if(ENABLE_PROFILE_GENERATE)
    add_compile_options(-fprofile-generate=${PROFILE_DIR})
    add_link_options(-fprofile-generate=${PROFILE_DIR})
    if(ENABLE_PROFILE_USE)
      message(WARNING "Both profile generate and profile use enabled")
    endif()
  elseif(ENABLE_PROFILE_USE)
    add_compile_options(-fprofile-use=${PROFILE_DIR})
    add_link_options(-fprofile-use=${PROFILE_DIR})
  endif()
elseif(ENABLE_PROFILE_GENERATE OR ENABLE_PROFILE_USE)
  message(WARNING "Profile Guided Optimization implemented only for GCC")
endif()